name: CI and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Check test coverage
      run: |
        COVERAGE_THRESHOLD=80
        COVERAGE=$(npx nyc report --reporter=text-summary | grep 'All files' | awk '{print $4}' | sed 's/%//')
        if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
          echo "Error: Test coverage is below $COVERAGE_THRESHOLD%. Coverage: $COVERAGE%"
          exit 1
        else
          echo "Success: Test coverage is above $COVERAGE_THRESHOLD%. Coverage: $COVERAGE%"
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Check code style
      run: |
        pip install flake8
        flake8 .

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
